name: Build project
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]
        build_arg1: [WITH_PCL=ON, WITH_PCL=OFF]
        build_arg2: [BUILD_EXAMPLE=ON, BUILD_EXAMPLE=OFF]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: "Install new cmake ubuntu"
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          sudo apt -y install curl
          echo "/usr/local/bin" >> $GITHUB_PATH
          curl -L https://github.com/Kitware/CMake/releases/download/v3.23.1/cmake-3.23.1-linux-x86_64.sh -o cmake.sh
          sudo sh cmake.sh --skip-license --prefix=/usr/local
      - name: "Setup deps macos"
        if: ${{ startsWith(matrix.os, 'macos') }}
        run: |
          brew update
          brew install cmake eigen pcl awk
      - name: "Setup deps ubuntu"
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          sudo apt -y update
          sudo apt -y install libeigen3-dev libpcl-dev
      - name: build
        run: |
          cd $GITHUB_WORKSPACE/
          mkdir build && cd build
          cmake .. -D${{ matrix.build_arg1 }} -D${{ matrix.build_arg2 }}
          sudo make install
