name: Build project
on:
  schedule:
    - cron: '0 * * * *'

  push:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04]
        build_arg1: [WITH_PCL=ON]
        build_arg2: [BUILD_EXAMPLE=ON]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: "Setup deps macos"
        if: ${{ startsWith(matrix.os, 'macos') }}
        run: |
          brew install eigen
          brew install pcl
      - name: "Setup deps ubuntu"
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          sudo apt -y update
          sudo apt -y install libeigen3-dev
          sudo apt -y install libpcl-dev
      - name: build
        run: |
          cd $GITHUB_WORKSPACE/
          mkdir build && cd build
          cmake .. -D${{ matrix.build_arg1 }} -D${{ matrix.build_arg2 }}
          sudo make install
